spring.application.name=align
spring.datasource.url=jdbc:postgresql://localhost:5432/align_db
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.username=postgres
spring.datasource.password=jhontamos
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=1010

springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
